## Put comments here that give an overall description of what your
## functions do

## This function takes a square invertible matrix as input and returns a list of
## 4 x functions: 1. to set the input matrix, 2. to get the input matrix, 3. to 
## set the inverse of the matrix, 4. to get the inverse of the matrix  

makeCacheMatrix <- function(x = matrix()) {
  s <- NULL
  set <- function(y) {
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setinv <- function(solve) s <<- solve
  getinv <- function() s
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## This function takes as argument the list generated by the function 
## makeCacheMatrix. It returns the inverse of the matrix injected as argument
## in function makeCacheMatrix, either from the cache if previously executed or
## by computing it.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  s <- x$getinv()
  if(!is.null(s)) {
    message("getting cached data")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setinv(s)
  s
}
